### ISSUE TITLE
Craft Commerce 3.0 Support

### ISSUE THREAD

**Issue by Mosnar** [surprisehighway/craft-avatax#15]
Just hoping to get a pulse on if it's on the roadmap!

**Comment by siffring** [comment]
@Mosnar Yes we plan to update for 3. Do you have a specific timeline you’re looking for?

**Comment by Mosnar** [comment]
Hoping to launch our project before the end of February, but take your time and do what you need to do!

**Comment by jlapan** [comment]
I also have a deployment happening before the end of the month and it would be awesome to be on Commerce 3!

**Comment by imagehat** [comment]
@Mosnar, @jlapan - just released a new version that is now Commerce 3 compatible.
