### ISSUE TITLE
Cannot edit plugin settings

### ISSUE THREAD

**Issue by j2is** [surprisehighway/craft-avatax#20]
All input fields in the settings are readonly and don't allow me to add text

**Comment by imagehat** [comment]
@j2is - did you set up a config file at `config/avatax.php`? If so any settings in that file will override the control panel settings fields and also make the field display as read only.

**Comment by j2is** [comment]
I haven't created that file, I wonder if it's because I'm using the commerce pro trial may be? I'm using commerce 3.1.7

**Comment by imagehat** [comment]
@j2is - looks like this was a bug, I just pushed a fix so updating to the latest version [2.1.1](https://github.com/surprisehighway/craft-avatax/releases/tag/v2.1.1) should resolve this issue.
