### ISSUE TITLE
Is this plugin a custom integration?

### ISSUE THREAD

**Issue by KatieMFritz** [surprisehighway/craft-avatax#23]
We got a [notice from Avatax](http://app.news.avalara.com/e/es?s=706&e=7376647&elqTrackId=c0464c8089704b199a72ab9f5a6ba13d&elq=ff3f8026a65544a1adce1658e553d1e5&elqaid=25348&elqat=1) that SSL cert updates are required for custom integration.

Is this plugin considered a custom integration? Do we need to do anything on our site?

Thanks!

**Comment by KatieMFritz** [comment]
Boosting

**Comment by imagehat** [comment]
Hi @KatieMFritz - this is technically a custom integration that calls the Avatax API but it doesn't download or install their local certificate files so their SSL renewals should have no impact on the plugin usage.

It looks like they last changed their certificates in late 2018 and we didn't have any issues then with the Craft 2 version then that uses the same Avalara PHP SDK.
