### ISSUE TITLE
 Request to avatax.com failed

### ISSUE THREAD

**Issue by knynkwl** [surprisehighway/craft-avatax#31]
We are running into this error. Any idea where this error is coming from or how to fix it? 

`[Error] Request to avatax.com failed`

**Comment by siffring** [comment]
@knynkwl that's a general connection failure message. Are you getting that error for every request? Was it working at some point?

Does the ["Test Connection" button](https://github.com/surprisehighway/craft-avatax#configuring-avatax-account-connection) work for you in the control panel settings?

**Comment by knynkwl** [comment]
Looks like validation is working. We get this error at any point trying to update a customer's address.

![Screen Shot 2021-04-20 at 12 47 10 PM](https://user-images.githubusercontent.com/4225771/115434291-887e8b80-a1d6-11eb-9fb3-69a72b9a7d0d.png)

**Comment by knynkwl** [comment]
When updating an address:

![Screen Shot 2021-04-20 at 12 48 32 PM](https://user-images.githubusercontent.com/4225771/115434467-b9f75700-a1d6-11eb-8549-37ab5d116df5.png)

**Comment by imagehat** [comment]
@knynkwl - you could try disabling address verification in the [plugin settings](https://github.com/surprisehighway/craft-avatax#configuring-avatax-plugin-options). Avalara's address validation is super strict. Also if you turn on debugging you should see the full request and response from Avalara in the log, which might help verify if the issue is just a bad address (or one Avalara thinks is bad).

**Comment by knynkwl** [comment]
address verification is disabled :(

Enabling debugging setting doesn't give any more info, unfortunately.

![Screen Shot 2021-04-20 at 1 34 09 PM](https://user-images.githubusercontent.com/4225771/115439915-18bfcf00-a1dd-11eb-8d5c-9b2bfcd80645.png)

**Comment by knynkwl** [comment]
Hey so I think it may be helpful to create some other errors based on the response. 

When returning the response in your plugin I get two different things.

When Address Validation is enabled:
```
Client error: `GET https://sandbox-rest.avatax.com/api/v2/addresses/resolve?line1=*******&line2=&line3=&city=*********&country=US&textCase=Mixed` resulted in a `401 Unauthorized` response:
{"error":{"code":"SubscriptionRequired","message":"This API requires a subscription to AutoAddress.","target":"CustomerA (truncated...)
```
General Connection:
```
Client error: `POST https://sandbox-rest.avatax.com/api/v2/transactions/create` resulted in a `401 Unauthorized` response:
{"error":{"code":"SubscriptionRequired","message":"This API requires a subscription to AvaTaxPro or BasicReturns.","targ (truncated...)
```

It might be better to log the error response so we know the issue.

**Comment by knynkwl** [comment]
For example, this would be much more helpful.

<img width="339" alt="Screen Shot 2021-04-20 at 2 15 19 PM" src="https://user-images.githubusercontent.com/4225771/115444656-d8634f80-a1e2-11eb-9764-e6bf25b70bca.png">

![Screen Shot 2021-04-20 at 2 14 48 PM](https://user-images.githubusercontent.com/4225771/115444604-c681ac80-a1e2-11eb-93bf-a0541a330523.png)
