### ISSUE TITLE
Cart passing all items as non-taxable

### ISSUE THREAD

**Issue by joshparylak** [surprisehighway/craft-avatax#33]
I'm connecting properly to the plugin, but I'm returning $0 in shipping. When I look at the response generated in the logs, the problem seems to be that `isItemTaxable` is set to false on all line items, which causes the cart amount to come through as exempt.

I'm not doing anything to declare items non-taxable, so I'm not sure why they are.

I do have a custom adjuster in place to handle quantity based discounts, but it wasn't interfering with Craft Commerce's default tax calculations.

**Comment by joshparylak** [comment]
This ended up being a configuration issue on the Avalara end, so I'm closing this out.

**Comment by siffring** [comment]
Thanks for letting us know @joshparylak.
