### ISSUE TITLE
$model is undefined - SalesTaxService.php

### ISSUE THREAD

**Issue by curtismorte** [surprisehighway/craft-avatax#35]
**Craft Version:** 3.6.14
**Craft Commerce Version:** 3.2.14.1
**Craft Avatax Version:** 2.1.3
**PHP Version:** 8.0.2

## $model is undefined in /src/services/SalesTaxService.php on line 714
When running `craft-avatax` in a production context (`'devMode' => false`), we get an internal server error because the variable `$model` is undefined. Specifically speaking, the errors happens [here](https://github.com/surprisehighway/craft-avatax/blob/master/src/services/SalesTaxService.php#L714) when `$model` is used within the logging statement. 

The source of the problem is that `$model` is only defined when devMode is enabled. See [here](https://github.com/surprisehighway/craft-avatax/blob/master/src/services/SalesTaxService.php#L685).

> This issue is related to #34

**Comment by siffring** [comment]
Thanks @curtismorte. We'll get this fixed.
