### ISSUE TITLE
Does this plugin support international fees? (Customs / VAT / etc). 

### ISSUE THREAD

**Issue by joshuapease** [surprisehighway/craft-avatax#46]
Hi There! I was curious if this plugin supports tax & fee calculations for international purchases. 

It didn't seem like it from a quick browse of the source code, but I thought I'd check.

**Comment by imagehat** [comment]
Hi @joshuapease - You are correct this plugin only integrates the sales and use tax calculations for US jurisdictions, not VAT/GST.
