### ISSUE TITLE
Commerce V4, Address Validation Fails - Calling Unknown Method SalesTaxService:getState() 

### ISSUE THREAD

**Issue by curtismorte** [surprisehighway/craft-avatax#49]
Hey Guys,
There's a bug with the address validation controller endpoint: `actions/avatax/json/validate-address`

Before making your plugin compatible with Commerce v4, you had the following method inside of `SalesTaxService.php`:
https://github.com/surprisehighway/craft-avatax/blob/9c0a6c77cc1d390535156ed3411f77b0534369b8/src/services/SalesTaxService.php#L723

> Since Craft Commerce no longer controls Addresses (they are a part of Craft CMS now), the model for Address changed. In doing so, the `stateId` / `stateText` field is no longer used. 
You can read more on countries and states [here](https://craftcms.com/docs/commerce/4.x/upgrading.html#countries-and-states).

It's my understanding that `administrativeArea` is now the appropriate field on the Address model for what most people consider a state / province. From the Craft CMS link above:
> While Commerce has removed support for managing custom countries and states, the [commerce/upgrade](https://craftcms.com/docs/commerce/4.x/console-commands.html#commerce-upgrade) command prompts you to map the custom countries to real country codes, and copies the state abbreviation (if a custom state was created) or the stateName entered by the customer to the administrativeArea field on relevant addresses and zones.

So it looks like all we need to do is update `$state = $this->getState($address);` to be `$state = $address->administrativeArea`:
https://github.com/surprisehighway/craft-avatax/blob/c497b63782d9cd2c9ea7075436ee09755c9a70bc/src/services/SalesTaxService.php#L759

**Comment by imagehat** [comment]
Oops, I thought I caught all the address changed. You are right, thanks, I can push a fix for this later today.
