### ISSUE TITLE
Craft 5 Compatibility? 

### ISSUE THREAD

**Issue by mrbenito** [surprisehighway/craft-avatax#51]
We are implementing a new commerce instance for our client and want to lean on Craft 5. The client uses Avalara to handle tax calculations. Do you have plans to update the plugin for Craft 5 compatibility?

**Comment by imagehat** [comment]
@mrbenito - We're definitely going to do a Craft 5 compatibility update. It's on our radar should hopefully be in the next week or two.

**Comment by imagehat** [comment]
@mrbenito - We just released a new version for Craft 5. #52
