### ISSUE TITLE
"Invalid plugin" error when trying to install plugin

### ISSUE THREAD

**Issue by jlapan** [surprisehighway/craft-avatax#6]
I am receiving the following error when trying to install the craft-avatax plugin on my local Craft site: 

surprisehighway/craft-avatax has been added, but an error occurred when installing it. Invalid plugin: No plugin exists with the handle "avalara-avatax".

![Screen Shot 2019-07-31 at 5 22 20 PM](https://user-images.githubusercontent.com/45296777/62249514-982dbf00-b3b8-11e9-8c8c-584bdd1e58c4.png)

**Comment by imagehat** [comment]
@jlapan - It looks like the plugin handle was set wrong when we submitted it to the plugin store. It should work to install manually via composer in the meantime, but I'll see what we can do to get it fixed in the plugin store though.

**Comment by jlapan** [comment]
@imagehat - Thanks, installing via composer worked fine.

**Comment by imagehat** [comment]
Pixel & Tonic was able to update the handle in the plugin store so closing this issue.

**Comment by jlapan** [comment]
Thanks
[image: Britten, Inc Logo] <https://britteninc.com/>

Jake LaPan

Web Developer

O: 231.346.8596 | M: 231.534.4185
[image: Building Wraps by Britten, Inc.]
<https://britteninc.com/request-a-quote/?i=decor>

Contact us today for pricing and a free conceptual sketch, no strings
attached!
